
import { Translation } from './types';

export const TRANSLATIONS: Record<'TH' | 'EN', Translation> = {
  TH: {
    title: 'ลงทะเบียนสนับสนุนกิจกรรมวันเด็กแห่งชาติ 2569',
    schoolName: 'โรงเรียนสาธิตอุดมศึกษา',
    eventDate: 'วันศุกร์ที่ 9 มกราคม พ.ศ. 2569',
    eventTime: 'เริ่มกิจกรรม 13.00 น.',
    setupInfo: 'จัดบูทได้ตั้งแต่เวลา 12.30 น. เป็นต้นไป',
    parentInfo: 'ข้อมูลผู้ปกครอง',
    studentInfo: 'ข้อมูลนักเรียน',
    supportDetails: 'รายละเอียดการสนับสนุน',
    logistics: 'รูปแบบการเข้าร่วมและอุปกรณ์',
    others: 'หมายเหตุเพิ่มเติม',
    required: '(จำเป็น)',
    optional: '(ถ้ามี)',
    submit: 'ส่งข้อมูลลงทะเบียน',
    submitting: 'กำลังส่งข้อมูล...',
    success: 'ขอบพระคุณสำหรับการลงทะเบียนร่วมสนับสนุนกิจกรรมวันเด็ก',
    back: 'กลับสู่หน้าหลัก',
    labelParentName: 'ชื่อ-นามสกุล ผู้ปกครอง',
    labelPhone: 'เบอร์โทรศัพท์ติดต่อ',
    labelLineId: 'Line ID',
    labelEmail: 'อีเมล',
    labelStudentName: 'ชื่อ-นามสกุล นักเรียน',
    labelGrade: 'ระดับชั้น / ห้อง',
    labelProgram: 'โปรแกรมการเรียน',
    labelSupportType: 'ประเภทการสนับสนุน',
    labelItemName: 'รายการอาหาร / ขนม / ของว่าง',
    labelQuantity: 'จำนวนโดยประมาณ (ชุด/ชิ้น)',
    labelCookOnSite: 'มีการประกอบอาหารหน้างานหรือไม่',
    labelParticipationMode: 'รูปแบบการเข้าร่วม',
    labelSetupTime: 'เวลาที่คาดว่าจะเข้าจัดบูท',
    labelNeedTable: 'ต้องการโต๊ะจากทางโรงเรียนหรือไม่ (ทางโรงเรียนจัดเตรียมให้สำหรับผู้จัดบูท)',
    labelNotes: 'ข้อเสนอแนะเพิ่มเติม / รายละเอียดอื่นๆ',
    optThaiProg: 'โปรแกรมภาษาไทย (Thai Programme)',
    optEngProg: 'โปรแกรมภาษาอังกฤษ (English Programme)',
    optFood: 'อาหาร',
    optDessert: 'ขนม',
    optSnack: 'ของว่าง',
    optDrink: 'เครื่องดื่ม',
    optSelf: 'จัดบูทแจกจ่ายด้วยตนเอง',
    optYes: 'ใช่ / มี',
    optNo: 'ไม่ใช่ / ไม่มี',
    placeholderName: 'ระบุชื่อ-นามสกุล',
    placeholderPhone: 'ระบุเบอร์โทรศัพท์ 10 หลัก',
    placeholderItem: 'เช่น ข้าวมันไก่, โดนัท, น้ำส้ม',
    placeholderQty: 'ระบุจำนวน เช่น 100 ชุด',
  },
  EN: {
    title: 'Children\'s Day 2026 Support Registration',
    schoolName: 'Satit Udomseuksa School',
    eventDate: 'Friday, January 9, 2026',
    eventTime: 'Activity starts at 1:00 PM',
    setupInfo: 'Booth setup available from 12:00 PM onwards',
    parentInfo: 'Parent Information',
    studentInfo: 'Student Information',
    supportDetails: 'Support Details',
    logistics: 'Participation & Equipment',
    others: 'Other Notes',
    required: '(Required)',
    optional: '(Optional)',
    submit: 'Submit Registration',
    submitting: 'Submitting...',
    success: 'Thank you for supporting our Children\'s Day activity!',
    back: 'Back to home',
    labelParentName: 'Parent Name-Surname',
    labelPhone: 'Contact Phone Number',
    labelLineId: 'Line ID',
    labelEmail: 'Email Address',
    labelStudentName: 'Student Name-Surname',
    labelGrade: 'Level',
    labelProgram: 'Academic Programme',
    labelSupportType: 'Support Category',
    labelItemName: 'Item Name (Food / Dessert / Snack / Drink)',
    labelQuantity: 'Estimated Quantity (Portions/Items)',
    labelCookOnSite: 'Will there be on-site cooking?',
    labelParticipationMode: 'Participation Type',
    labelSetupTime: 'Expected Setup Time',
    labelNeedTable: 'Do you require a table? (Provided by school for booths)',
    labelNotes: 'Additional Suggestions / Notes',
    optThaiProg: 'Thai Programme',
    optEngProg: 'English Programme',
    optFood: 'Main Food',
    optDessert: 'Dessert',
    optSnack: 'Snacks',
    optDrink: 'Drinks',
    optSelf: 'Setup booth and distribute personally',
    optYes: 'Yes',
    optNo: 'No',
    placeholderName: 'Enter Full Name',
    placeholderPhone: 'Enter 10-digit number',
    placeholderItem: 'e.g., Fried Rice, Donuts, Orange Juice',
    placeholderQty: 'e.g., 100 sets',
  }
};
